#!/usr/bin/env bash

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Check for required commands
REQUIRED_CMDS=("notify-send" "xdg-screensaver" "ffplay")
for cmd in "${REQUIRED_CMDS[@]}"; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "$cmd is required to run this script"
        exit 1
    fi
done

# Set up Python virtual environment if it doesn't exist
if [ ! -d "$DIR/venv" ]; then
    /usr/bin/env python3 -m venv --system-site-packages "$DIR/venv"
    source "$DIR/venv/bin/activate"
    /usr/bin/env python3 -m pip install -r "$DIR/requirements.txt"
    echo
else
    source "$DIR/venv/bin/activate"
fi

# Run the Python script with all passed arguments
/usr/bin/env python3 "$DIR/start.py" "$@"
